Add compute_samples_displays method to SimulatesSamples (#1257)
Comes after #1252 

Since SimulatesSamples and SimulatesIntermediateWaveFunction both have `compute_displays` methods with different signatures, mypy complains about classes that inherit from both:
```
cirq/sim/sparse_simulator.py:27: error: Definition of "compute_displays" in base class "SimulatesIntermediateWaveFunction" is incompatible with definition in base class "SimulatesSamples"
cirq/google/sim/xmon_simulator.py:96: error: Definition of "compute_displays" in base class "SimulatesIntermediateWaveFunction" is incompatible with definition in base class "SimulatesSamples"
```
Is this actually a problem?

Also, I don't understand why pylint is making the following complaint:
```
cirq/sim/sparse_simulator_test.py:439:19: E1003: Bad first argument 'SimulatesIntermediateWaveFunction' given to super() (bad-super-call)
cirq/sim/sparse_simulator_test.py:443:19: E1003: Bad first argument 'SimulatesIntermediateWaveFunction' given to super() (bad-super-call)
```