Fixes for older envs (#3836)
These are failing on older envs, so adding them here for now. 

1. importing mpl_toolkits plot3d: Old matplotlib versions cause failures: `ValueError: Unknown projection '3d'`
2. older numpy versions didn't have `random()` on `RandomState` only `rand()`, otherwise the failure is: `AttributeError: 'mtrand.RandomState' object has no attribute 'random'`