Bump up the minimum required version of ply (#5890)
Avoid the test failure in `sycamore_gate_test.py` such as follows:

```
$ pytest -x -q cirq-google/cirq_google/ops/sycamore_gate_test.py::test_consistent_protocols
...
        if not optimize:
            if linfo.validate_all():
>               raise SyntaxError("Can't build lexer")
E               SyntaxError: Can't build lexer

/tmp/t39/lib/python3.9/site-packages/ply/lex.py:894: SyntaxError
-------------------------------------------- Captured stderr call --------------------------------------------
ERROR: /tmp/t39/lib/python3.9/site-packages/qiskit/qasm/qasmlexer.py:191: No regular expression defined for rule 't_eof'
```